### PR TITLE
candidates_terms, boards API modification

### PR DESCRIPTION
**Pull request by ichiaohsu**
1. candidates_term support embedded latest boards
2. Default sorting: candidates_terms -> id, boards -> -uploaded_at
3. boards modified fields to fit spec

### CODE REVIEW

**Comment by hcchien** [comment]
What does the id look like?

**Comment by ichiaohsu** [comment]
@hcchien In Django default id is auto_increment unique integer

**Comment by hcchien** [comment]
okay, then i don't think that we should sort by id. maybe we can sort by type（縣市長/縣市議員）and city?

**Comment by ichiaohsu** [comment]
If we are going to use county and type, I think there should be more fields included. As far as I know, when @tempo0829 consume `candidates_terms` API, he will explicitly use restrictions like `county=臺北市` and `type=councilors`. If he apply both restrains, the result will have no sort reference and the pagination result could probably be wrong. Maybe we could consider `name` field?

**Comment by hcchien** [comment]
ok, I see. it the users pass the params including the country and type,
sort by id would be fine.

**Comment by ichiaohsu** [comment]
I'm not sure about @tempo0829's use case. My original intention was to make it sorted in `county`, `district`,  and `name`(or `id`) order so that when client-side request with both parameters like `county=臺北市&type=councilors` we still have third sort order option(`name` or `id`) to keep the pagination correct. 

I believe there is a practical situation in our page that need request with both parameters. It seems better to decide this PR after we include @tempo0829's opinion.

**Comment by ichiaohsu** [comment]
Default sort change to `county`, `type`, `id`. Are we good to go, @hcchien ?

**Pull request merged**
